### ISSUE TITLE
Expert Data

### ISSUE THREAD

**Issue by melikbugra** [hcnoh/gail-pytorch#1]
Hello, can I generate expert data for CartPole environment? If so how can I do it?

**Comment by hcnoh** [comment]
Hello. You can generate the expert policy by any reinforcement learning algorithms such as TRPO.
If you want to use the GAIL with my repo, please check my RL repo: https://github.com/hcnoh/rl-collection-pytorch.
In the RL repo, you need to run the GAE or PPO and you can get the expert policies.

Thank you.

**Comment by melikbugra** [comment]
Thank you very much Sir. I really appreciate your help!
