### ISSUE TITLE
Error running CartPole-v1

### ISSUE THREAD

**Issue by deltawi** [hcnoh/gail-pytorch#4]
When I run 

```
python train.py --env_name=CartPole-v1
```

I get this error 
```
  File "gail-pytorch/models/nets.py", line 128, in act
    state = FloatTensor(state)
ValueError: expected sequence of length 4 at dim 1 (got 0)
```

**Comment by hcnoh** [comment]
I will check the error. May I ask you to let me know your OpenAI Gym version?

**Comment by deltawi** [comment]
> I will check the error. May I ask you to let me know your OpenAI Gym version?

```
>>> import gym
>>> gym.__version__
'0.21.0'
>>> 
```

**Comment by hcnoh** [comment]
The gym version on my machine is `0.18,0`. If you change the version to mine, you can run the project safely.
